spring:
  profiles:
    active: dev
---
server:
     port: 7001 #冒号后边要有空格
spring:
  profiles: dev
  application:
    name: springcloud-config-eureka-client
eureka:
  instance:
    hostname: eureka7001.com #
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: false
    fetch-registry: false
---
server:
  port: 7001 #冒号后边要有空格
spring:
  profiles: test
  application:
    name: springcloud-config-eureka-client
eureka:
  instance:
    hostname: eureka7001.com #
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: false
    fetch-registry: false